import time

def show_xavi_small():
    height = 27
    width = 40

    print('--- XAVI (Small 4:5) ---')
    time.sleep(0.5)

    for row in range(height):
        line = ""
        for col in range(width):
            char = " "

            if row == 0:
                if col == 0: char = "-"
                elif col == 1: char = "."
                elif col == 4: char = "."
                elif col == 7: char = "."
                elif 8 <= col <= 9: char = "="
                elif col == 10: char = "."
                elif col == 12: char = "."
                elif col == 14: char = "-"
                elif col == 15: char = "*"
                elif col == 16: char = "+"
                elif col == 17: char = "="
                elif col == 18: char = "-"
                elif col == 19: char = "+"
                elif 20 <= col <= 21: char = "-"
                elif col == 22: char = "*"
                elif 23 <= col <= 25: char = "@"
                elif col == 26: char = "%"
                elif 27 <= col <= 29: char = "*"
                elif col == 30: char = "="
                elif col == 31: char = "+"
                elif col == 32: char = "#"
                elif col == 33: char = "+"
                elif col == 34: char = "."
                elif col == 35: char = "="
                elif col == 36: char = "#"
                elif 37 <= col <= 39: char = "*"

            elif row == 1:
                if col == 0: char = "+"
                elif col == 1: char = "-"
                elif col == 7: char = ":"
                elif col == 8: char = "+"
                elif col == 9: char = "-"
                elif col == 12: char = ":"
                elif col == 13: char = "."
                elif col == 14: char = "-"
                elif col == 15: char = "+"
                elif col == 16: char = "#"
                elif col == 17: char = "*"
                elif 18 <= col <= 20: char = "%"
                elif col == 21: char = "#"
                elif col == 22: char = "*"
                elif col == 23: char = "+"
                elif col == 24: char = "%"
                elif col == 25: char = "@"
                elif 26 <= col <= 27: char = "#"
                elif col == 28: char = "%"
                elif col == 29: char = "#"
                elif col == 30: char = "*"
                elif col == 31: char = "#"
                elif col == 32: char = "@"
                elif col == 33: char = "*"
                elif 34 <= col <= 35: char = ":"
                elif col == 36: char = "#"
                elif 37 <= col <= 38: char = "%"
                elif col == 39: char = "*"

            elif row == 2:
                if col == 0: char = "#"
                elif col == 1: char = "+"
                elif col == 7: char = "."
                elif col == 8: char = ":"
                elif 9 <= col <= 12: char = "="
                elif col == 13: char = "-"
                elif col == 14: char = "+"
                elif col == 15: char = "@"
                elif col == 16: char = "#"
                elif col == 17: char = "%"
                elif 18 <= col <= 22: char = "@"
                elif col == 23: char = "%"
                elif col == 24: char = "+"
                elif col == 25: char = "#"
                elif 26 <= col <= 28: char = "@"
                elif col == 29: char = "+"
                elif col == 30: char = "-"
                elif col == 31: char = "+"
                elif col == 32: char = "%"
                elif col == 33: char = "@"
                elif col == 34: char = "*"
                elif col == 35: char = "="
                elif col == 36: char = "*"
                elif col == 37: char = "%"
                elif col == 38: char = "+"
                elif col == 39: char = "="

            elif row == 3:
                if col == 0: char = "*"
                elif col == 1: char = "="
                elif col == 6: char = "."
                elif col == 9: char = "+"
                elif col == 10: char = "*"
                elif col == 11: char = "="
                elif 12 <= col <= 13: char = "+"
                elif col == 14: char = "#"
                elif col == 15: char = "."
                elif col == 18: char = ":"
                elif col == 19: char = "="
                elif col == 20: char = ":"
                elif 23 <= col <= 24: char = "%"
                elif col == 25: char = "#"
                elif col == 26: char = "@"
                elif col == 27: char = "#"
                elif col == 28: char = "+"
                elif 29 <= col <= 31: char = "*"
                elif col == 32: char = "#"
                elif col == 33: char = "@"
                elif 34 <= col <= 35: char = "%"
                elif 36 <= col <= 37: char = "@"
                elif col == 38: char = "+"
                elif col == 39: char = "-"

            elif row == 4:
                if col == 0: char = "."
                elif col == 3: char = "*"
                elif col == 4: char = "+"
                elif col == 5: char = ":"
                elif 6 <= col <= 7: char = "+"
                elif col == 8: char = "="
                elif 9 <= col <= 10: char = "*"
                elif col == 11: char = "="
                elif col == 12: char = "*"
                elif col == 13: char = "%"
                elif col == 14: char = "."
                elif 24 <= col <= 25: char = "%"
                elif col == 26: char = "#"
                elif 27 <= col <= 28: char = "="
                elif 29 <= col <= 30: char = "@"
                elif col == 31: char = "%"
                elif col == 32: char = "*"
                elif col == 33: char = "#"
                elif 34 <= col <= 35: char = "%"
                elif 36 <= col <= 37: char = "@"
                elif col == 38: char = "*"
                elif col == 39: char = "="

            elif row == 5:
                if col == 0: char = ":"
                elif col == 2: char = ":"
                elif 3 <= col <= 7: char = "@"
                elif col == 8: char = "%"
                elif col == 9: char = "@"
                elif col == 10: char = "%"
                elif col == 11: char = "+"
                elif col == 12: char = "="
                elif col == 13: char = "#"
                elif col == 24: char = "#"
                elif col == 25: char = "%"
                elif col == 26: char = "*"
                elif col == 27: char = "+"
                elif col == 28: char = "="
                elif 29 <= col <= 30: char = "+"
                elif 31 <= col <= 32: char = "-"
                elif col == 33: char = "+"
                elif col == 34: char = "#"
                elif col == 35: char = "*"
                elif col == 36: char = "#"
                elif col == 37: char = "%"
                elif col == 38: char = "+"
                elif col == 39: char = "-"

            elif row == 6:
                if col == 0: char = "@"
                elif col == 1: char = "*"
                elif col == 2: char = "="
                elif col == 3: char = "+"
                elif 4 <= col <= 10: char = "@"
                elif col == 11: char = "="
                elif col == 12: char = ":"
                elif col == 13: char = "="
                elif col == 15: char = "."
                elif col == 16: char = "-"
                elif 24 <= col <= 25: char = "%"
                elif col == 26: char = "="
                elif col == 27: char = "."
                elif col == 32: char = "."
                elif col == 33: char = "-"
                elif 34 <= col <= 36: char = "*"
                elif col == 37: char = "#"
                elif col == 38: char = "*"
                elif col == 39: char = "+"

            elif row == 7:
                if 0 <= col <= 1: char = "@"
                elif col == 2: char = "="
                elif col == 3: char = ":"
                elif col == 4: char = "+"
                elif 5 <= col <= 6: char = "@"
                elif col == 7: char = "%"
                elif 8 <= col <= 9: char = "@"
                elif col == 10: char = "%"
                elif col == 11: char = "="
                elif col == 12: char = ":"
                elif col == 15: char = "-"
                elif col == 16: char = "#"
                elif col == 17: char = "="
                elif col == 19: char = "*"
                elif col == 20: char = "%"
                elif col == 21: char = "*"
                elif col == 22: char = ":"
                elif col == 24: char = "+"
                elif col == 25: char = "="
                elif col == 26: char = "-"
                elif 29 <= col <= 31: char = "."
                elif 32 <= col <= 33: char = ":"
                elif col == 34: char = "+"
                elif 35 <= col <= 39: char = "#"

            elif row == 8:
                if 0 <= col <= 1: char = "@"
                elif col == 2: char = "+"
                elif col == 3: char = ":"
                elif col == 4: char = "+"
                elif 5 <= col <= 6: char = "@"
                elif col == 7: char = "%"
                elif 8 <= col <= 9: char = "@"
                elif col == 10: char = "+"
                elif col == 11: char = ":"
                elif col == 16: char = "."
                elif col == 20: char = "-"
                elif col == 21: char = "."
                elif 24 <= col <= 25: char = "."
                elif col == 26: char = ":"
                elif 27 <= col <= 29: char = "."
                elif 30 <= col <= 31: char = ":"
                elif 32 <= col <= 34: char = "-"
                elif col == 35: char = "+"
                elif 36 <= col <= 39: char = "#"

            elif row == 9:
                if 0 <= col <= 1: char = "@"
                elif col == 2: char = "+"
                elif col == 3: char = "="
                elif col == 4: char = "%"
                elif 5 <= col <= 6: char = "@"
                elif 7 <= col <= 8: char = "#"
                elif col == 9: char = "+"
                elif col == 10: char = ":"
                elif col == 25: char = "#"
                elif col == 26: char = "="
                elif col == 27: char = "."
                elif 28 <= col <= 29: char = ":"
                elif 30 <= col <= 32: char = "-"
                elif col == 33: char = "="
                elif col == 34: char = "-"
                elif col == 35: char = "="
                elif col == 36: char = "*"
                elif 37 <= col <= 39: char = "#"

            elif row == 10:
                if 0 <= col <= 1: char = "@"
                elif col == 2: char = "+"
                elif col == 3: char = "="
                elif col == 4: char = "*"
                elif col == 5: char = "%"
                elif col == 6: char = "#"
                elif 7 <= col <= 8: char = "="
                elif 9 <= col <= 10: char = "+"
                elif col == 11: char = "*"
                elif 12 <= col <= 13: char = "@"
                elif col == 18: char = "."
                elif 25 <= col <= 26: char = "@"
                elif col == 27: char = "*"
                elif col == 28: char = ":"
                elif col == 29: char = "-"
                elif 30 <= col <= 36: char = "="
                elif 37 <= col <= 39: char = "#"

            elif row == 11:
                if col == 0: char = "*"
                elif col == 1: char = "="
                elif 2 <= col <= 3: char = "."
                elif col == 4: char = "-"
                elif col == 5: char = "*"
                elif col == 6: char = "#"
                elif 7 <= col <= 8: char = "*"
                elif 9 <= col <= 11: char = "%"
                elif 12 <= col <= 13: char = "@"
                elif col == 14: char = "."
                elif 16 <= col <= 17: char = "."
                elif col == 18: char = ":"
                elif col == 23: char = "."
                elif 24 <= col <= 27: char = "@"
                elif col == 28: char = "-"
                elif 29 <= col <= 31: char = "="
                elif 32 <= col <= 35: char = "+"
                elif 36 <= col <= 39: char = "="

            elif row == 12:
                if col == 2: char = ":"
                elif col == 3: char = "*"
                elif col == 4: char = "%"
                elif col == 5: char = "@"
                elif col == 6: char = "%"
                elif col == 7: char = "+"
                elif col == 8: char = "*"
                elif col == 9: char = "@"
                elif col == 10: char = "%"
                elif col == 11: char = "#"
                elif 12 <= col <= 13: char = "@"
                elif col == 14: char = "*"
                elif col == 16: char = "-"
                elif 17 <= col <= 20: char = ":"
                elif col == 23: char = "*"
                elif 24 <= col <= 27: char = "@"
                elif col == 28: char = "*"
                elif col == 29: char = "="
                elif 30 <= col <= 39: char = "+"

            elif row == 13:
                if col == 0: char = "-"
                elif col == 1: char = "#"
                elif 2 <= col <= 5: char = "@"
                elif col == 6: char = "%"
                elif col == 7: char = "="
                elif col == 8: char = "+"
                elif col == 9: char = "@"
                elif col == 10: char = "%"
                elif col == 11: char = "*"
                elif 12 <= col <= 14: char = "@"
                elif col == 15: char = "+"
                elif col == 17: char = ":"
                elif col == 18: char = "-"
                elif col == 19: char = "."
                elif 20 <= col <= 22: char = "-"
                elif col == 23: char = "@"
                elif col == 24: char = "*"
                elif 25 <= col <= 27: char = "@"
                elif col == 28: char = "*"
                elif 29 <= col <= 32: char = "+"
                elif 33 <= col <= 39: char = "*"

            elif row == 14:
                if 0 <= col <= 6: char = "@"
                elif col == 7: char = "+"
                elif col == 8: char = "*"
                elif col == 9: char = "@"
                elif 10 <= col <= 11: char = "%"
                elif 12 <= col <= 15: char = "@"
                elif col == 16: char = "-"
                elif col == 17: char = "."
                elif 18 <= col <= 19: char = ":"
                elif col == 20: char = "*"
                elif col == 21: char = "="
                elif col == 22: char = "*"
                elif col == 23: char = "@"
                elif col == 24: char = "%"
                elif 25 <= col <= 27: char = "@"
                elif col == 28: char = "*"
                elif 29 <= col <= 31: char = "+"
                elif 32 <= col <= 39: char = "*"

            elif row == 15:
                if 0 <= col <= 6: char = "@"
                elif 7 <= col <= 8: char = "="
                elif col == 9: char = "%"
                elif col == 10: char = "+"
                elif col == 11: char = "%"
                elif 12 <= col <= 27: char = "@"
                elif col == 28: char = "#"
                elif col == 29: char = "*"
                elif 30 <= col <= 31: char = "%"
                elif 32 <= col <= 33: char = "#"
                elif 34 <= col <= 39: char = "*"

            elif row == 16:
                if 0 <= col <= 4: char = "@"
                elif col == 5: char = "%"
                elif 6 <= col <= 8: char = "+"
                elif 9 <= col <= 10: char = "*"
                elif 11 <= col <= 26: char = "@"
                elif col == 27: char = "%"
                elif col == 28: char = "+"
                elif col == 29: char = "="
                elif col == 30: char = "#"
                elif col == 31: char = "%"
                elif 32 <= col <= 35: char = "@"
                elif 36 <= col <= 37: char = "%"
                elif 38 <= col <= 39: char = "#"

            elif row == 17:
                if 0 <= col <= 3: char = "@"
                elif 4 <= col <= 5: char = "#"
                elif 6 <= col <= 15: char = "@"
                elif col == 16: char = "+"
                elif col == 17: char = "%"
                elif 18 <= col <= 24: char = "@"
                elif 25 <= col <= 26: char = "%"
                elif 27 <= col <= 28: char = "#"
                elif col == 29: char = "*"
                elif 30 <= col <= 32: char = "+"
                elif 33 <= col <= 37: char = "@"
                elif col == 38: char = "%"
                elif col == 39: char = "#"

            elif row == 18:
                if 0 <= col <= 3: char = "@"
                elif col == 4: char = "#"
                elif 5 <= col <= 15: char = "@"
                elif col == 16: char = "-"
                elif col == 17: char = "%"
                elif 18 <= col <= 22: char = "@"
                elif 23 <= col <= 29: char = "%"
                elif 30 <= col <= 31: char = "@"
                elif col == 32: char = "#"
                elif col == 33: char = "*"
                elif 34 <= col <= 35: char = "@"
                elif 36 <= col <= 39: char = "%"

            elif row == 19:
                if 0 <= col <= 2: char = "@"
                elif col == 3: char = "%"
                elif 4 <= col <= 23: char = "@"
                elif col == 24: char = "%"
                elif col == 25: char = "@"
                elif 26 <= col <= 28: char = "%"
                elif 29 <= col <= 32: char = "@"
                elif col == 33: char = "%"
                elif col == 34: char = "*"
                elif 35 <= col <= 38: char = "%"
                elif col == 39: char = "@"

            elif row == 20:
                if 0 <= col <= 33: char = "@"
                elif col == 34: char = "%"
                elif col == 35: char = "#"
                elif col == 36: char = "+"
                elif col == 37: char = "-"
                elif col == 38: char = "+"
                elif col == 39: char = "%"

            elif row == 21:
                if 0 <= col <= 34: char = "@"
                elif col == 35: char = "%"
                elif col == 36: char = ":"
                elif col == 38: char = ":"
                elif col == 39: char = "="

            elif row == 22:
                if 0 <= col <= 35: char = "@"
                elif col == 36: char = "="
                elif col == 38: char = "."
                elif col == 39: char = ":"

            elif row == 23:
                if 0 <= col <= 16: char = "@"
                elif col == 17: char = "#"
                elif 18 <= col <= 35: char = "@"
                elif col == 36: char = "*"
                elif col == 39: char = ":"

            elif row == 24:
                if 0 <= col <= 15: char = "@"
                elif col == 16: char = "%"
                elif col == 17: char = "#"
                elif 18 <= col <= 36: char = "@"
                elif col == 37: char = "-"
                elif col == 38: char = "."
                elif col == 39: char = "="

            elif row == 25:
                if 0 <= col <= 36: char = "@"
                elif col == 37: char = "#"
                elif col == 38: char = ":"
                elif col == 39: char = "+"

            elif row == 26:
                if 0 <= col <= 7: char = "@"
                elif col == 8: char = "%"
                elif 9 <= col <= 37: char = "@"
                elif col == 39: char = "="

            line += char
        print(line)
        time.sleep(0.05)

if __name__ == '__main__':
    show_xavi_small()