# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rCgUsE1b7gX_1zfYpLr0T05IW3sTImE0
"""

import gradio as gr
from PIL import Image, ImageDraw, ImageFont

ASCII = " .,:;+=*"

def generate(img):
    img = img.resize((130, int(130 * img.height / img.width * 0.45)))
    img = img.convert("RGB")

    w, h = img.size
    chars = []
    colors = []

    for y in range(h):
        row_c = []
        row_col = []
        for x in range(w):
            r, g, b = img.getpixel((x, y))
            br = (r + g + b) // 3

            if br > 240: ch = " "
            elif br > 220: ch = "."
            elif br > 200: ch = ","
            elif br > 180: ch = ":"
            elif br > 160: ch = ";"
            elif br > 140: ch = "+"
            elif br > 110: ch = "="
            else: ch = "*"

            row_c.append(ch)
            row_col.append((r, g, b))

        chars.append(row_c)
        colors.append(row_col)

    font = ImageFont.load_default()
    cw, ch = 6, 10

    canvas = Image.new("RGB", (w*cw, h*ch), "black")
    draw = ImageDraw.Draw(canvas)

    for y in range(h):
        for x in range(w):
            draw.text((x*cw, y*ch), chars[y][x], fill=colors[y][x], font=font)

    file_path = "ascii_output.png"
    canvas.save(file_path)

    return canvas, file_path


default_image = Image.open("xavi.jpg")

with gr.Blocks() as app:
    gr.Markdown("# 🎨 ASCII PNG Generator")

    with gr.Row():
        img = gr.Image(value=default_image, type="pil", label="Input Image")
        out = gr.Image(label="ASCII Output")

    btn = gr.Button("Convert")
    file = gr.File(label="Download PNG")

    btn.click(generate, img, [out, file])

app.launch()

