# -*- coding: utf-8 -*-
"""imageapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FEcPEagRf9_9nuvsE1OSICVZ2vj5rXM8

Xavi Hernandez-ASCIII image
"""

from PIL import Image

img = Image.open("xavi.jpg")   # your Xavi photo
img

from PIL import Image

# only light & medium characters – no heavy black ink
ASCII = " .,:;+=*"

img = Image.open("xavi.jpg")
img = img.resize((130, int(130 * img.height / img.width * 0.45)))
img = img.convert("RGB")

w, h = img.size

for y in range(h):
    for x in range(w):
        r, g, b = img.getpixel((x, y))
        br = (r + g + b) // 3

        if br > 240:
            ch = " "
        elif br > 220:
            ch = "."
        elif br > 200:
            ch = ","
        elif br > 180:
            ch = ":"
        elif br > 160:
            ch = ";"
        elif br > 140:
            ch = "+"
        elif br > 110:
            ch = "="
        else:
            ch = "*"   # darkest, but still not black

        print(f"\033[38;2;{r};{g};{b}m{ch}", end="")
    print("\033[0m")

print("\nXAVI HERNÁNDEZ – No Black Face ASCII")

"""Conclusion:

In this project, a real image of Xavi Hernández was converted into ASCII art using Python and the Pillow library.
The program reads an image, converts it into grayscale, resizes it, and maps pixel brightness to ASCII characters.
This approach helps in understanding how digital images are represented using pixel intensity and how those values can be transformed into text-based art.
The final output successfully produces a recognizable ASCII portrait, demonstrating the practical use of image processing and logical mapping in Python.

"""

